// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sigma_weights
arma::mat sigma_weights(int n, double alpha, double kappa, double betta);
RcppExport SEXP filters_sigma_weights(SEXP nSEXP, SEXP alphaSEXP, SEXP kappaSEXP, SEXP bettaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type betta(bettaSEXP);
    __result = Rcpp::wrap(sigma_weights(n, alpha, kappa, betta));
    return __result;
END_RCPP
}
// sigma_pts
arma::mat sigma_pts(arma::vec m, arma::mat P, int n, double alpha, double kappa, double betta);
RcppExport SEXP filters_sigma_pts(SEXP mSEXP, SEXP PSEXP, SEXP nSEXP, SEXP alphaSEXP, SEXP kappaSEXP, SEXP bettaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type betta(bettaSEXP);
    __result = Rcpp::wrap(sigma_pts(m, P, n, alpha, kappa, betta));
    return __result;
END_RCPP
}
// chol_test
arma::mat chol_test(arma::mat M);
RcppExport SEXP filters_chol_test(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    __result = Rcpp::wrap(chol_test(M));
    return __result;
END_RCPP
}
