# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigma_weights <- function(n, alpha = 1e-03, kappa = 0, betta = 2) {
    .Call('filters_sigma_weights', PACKAGE = 'filters', n, alpha, kappa, betta)
}

sigma_pts <- function(m, P, n, alpha = 1e-03, kappa = 0, betta = 2) {
    .Call('filters_sigma_pts', PACKAGE = 'filters', m, P, n, alpha, kappa, betta)
}

chol_test <- function(M) {
    .Call('filters_chol_test', PACKAGE = 'filters', M)
}

